const { authJwt } = require("../middleware");
const controller = require("../controllers/helper.controller");
module.exports = function (app) {
    app.post(
        "/api/ShipmentReport/GetAllPaginationExternalupdate",
        [authJwt.verifyToken],
        controller.GetAllPaginationExternalupdate
    );
    app.get(
        "/api/Client/MerchantNames",
        [authJwt.verifyToken],
        controller.MerchantNames
    );
    app.get(
        "/api/ShipmentReport/GetByTrackingNo/:id",
        [authJwt.verifyToken],
        controller.GetShipmentByTrackingNo
    );
    app.get(
        "/api/Orders/GetByTracking/:id",
        [authJwt.verifyToken],
        controller.GetByTracking
    );
    app.post(
        "/api/CustomersAction/EditPhone",
        [authJwt.verifyToken],
        controller.EditPhone
    );
    app.post(
        "/api/CustomersAction/EditAddress",
        [authJwt.verifyToken],
        controller.EditAddress
    );
    app.post(
        "/api/CustomersAction/SelfCollectRequest",
        [authJwt.verifyToken],
        controller.SelfCollectRequest
    );
    app.post(
        "/api/CustomersAction/AddAction/:id",
        [authJwt.verifyToken],
        controller.AddAction
    );
    app.post(
        "/api/View_CustomersActions/GetAllPagingFilter",
        [authJwt.verifyToken],
        controller.GetAllPagingFilter
    );
    app.post(
        "/api/View_CustomersActions/GetAllOPSDonePagingFilter",
        [authJwt.verifyToken],
        controller.GetAllOPSDonePagingFilter
    );
    app.post(
        "/api/ShipmentReport/GetAllOnHoldPaginationExternalupdate",
        [authJwt.verifyToken],
        controller.GetAllOnHoldPaginationExternalupdate
    );
    app.get(
        "/api/OrderTransactionTypes/GetAll",
        [authJwt.verifyToken],
        controller.OrderTransactionTypesGetAll
    );
    app.get(
        "/api/Depots/GetAll",
        [authJwt.verifyToken],
        controller.GetAllHubs
    );
    app.post(
        "/api/View_CustomersActions/GetAllOPSPagingFilter",
        [authJwt.verifyToken],
        controller.GetAllOPSPagingFilter
    );
    app.post(
        "/api/CustomersAction/MarkAsDone",
        [authJwt.verifyToken],
        controller.MarkAsRead
    );
    app.get(
        "/api/ShipmentReport/GetAllOnHoldGroupBy/:id",
        [authJwt.verifyToken],
        controller.GetAllOnHoldGroupBy
    );
    app.get(
        "/api/View_CustomersActions/GetById/:id",
        [authJwt.verifyToken],
        controller.CustomerActionById
    );
    app.post(
        "/api/CustomersAction/MarkAsreject",
        [authJwt.verifyToken],
        controller.MarkAsreject
    );
    app.post(
        "/api/View_COD_Report/FilterReportStatusUpdated",
        [authJwt.verifyToken],
        controller.FilterReportStatusUpdated
    );
    app.post(
        "/api/CustomersAction/ImportCustomerRequests",
        [authJwt.verifyToken],
        controller.ImportCustomerRequests
    );
    app.get(
        "/api/SMS_Log/GetById/:id",
        [authJwt.verifyToken],
        controller.GetSmsLogById
    );
    app.post(
        "/api/CustomersAction/AddCall",
        [authJwt.verifyToken],
        controller.AddCall
    );
    app.post(
        "/api/ShipmentReport/FilterReportStatusUpdated",
        [authJwt.verifyToken],
        controller.ShipmentReportFilterReportStatusUpdated
    );
    app.get(
        "/api/Client/GetAllPagination",
        [authJwt.verifyToken],
        controller.GetClientAllPagination
    );
    app.post(
        "/api/Custom/ImportCustomDuty",
        [authJwt.verifyToken],
        controller.ImportCustomDuty
    );
    app.post(
        "/api/Custom/GetCustomDutyReport",
        [authJwt.verifyToken],
        controller.GetCustomDutyReport
    );
    app.post(
        "/api/Custom/GenerateInvoiceXml",
        [authJwt.verifyToken],
        controller.GenerateInvoiceXml
    );    
    app.post(
        "/api/Custom/GetMasterData",
        [authJwt.verifyToken],
        controller.GetMasterData
    );    
    app.post(
        "/api/Custom/UploadCustomDutyToErp",
        [authJwt.verifyToken],
        controller.UploadCustomDutyToErp
    );        
    app.post(
        "/api/Custom/UploadInvoiceXmlToAmazon",
        [authJwt.verifyToken],
        controller.UploadInvoiceXmlToAmazon
    );
    app.post(
        "/api/Custom/GetAmazonInvoiceHistory",
        [authJwt.verifyToken],
        controller.GetAmazonInvoiceHistory
    );
    app.post(
        "/api/Custom/GenerateCn35Bill",
        [authJwt.verifyToken],
        controller.GenerateCn35Bill
    );
    app.get(
        "/api/events-status-code",
        [authJwt.verifyToken],
        controller.GetEventsStatusCodes
    )
    app.post(
        "/api/Custom/ImportIntlCustomDuty",
        [authJwt.verifyToken],
        controller.ImportIntlCustomDuty
    );
    app.post(
        "/api/Custom/InsertFlightArrivalDetail",
        [authJwt.verifyToken],
        controller.InsertFlightArrivalDetail
    );
    app.post(
        "/api/Custom/UpdateFlightArrivalDetail",
        [authJwt.verifyToken],
        controller.UpdateFlightArrivalDetail
    );
    app.post(
        "/api/Custom/GetFlightArrivalDetails",
        [authJwt.verifyToken],
        controller.GetFlightArrivalDetails
    );
    app.post(
        "/api/Custom/GetFlightArrivalReport",
        [authJwt.verifyToken],
        controller.GetFlightArrivalReport
    );    
    app.get(
        "/api/Whatsapp_Log/GetById/:id",
        [authJwt.verifyToken],
        controller.GetWhatsappLogs
    );
    app.post(
        "/api/Custom/GenerateTemuCodReport",
        [authJwt.verifyToken],
        controller.GenerateTemuCodReport
    );
    app.post(
        "/api/Custom/GetTemuCodHistory",
        [authJwt.verifyToken],
        controller.GetTemuCodHistory
    ); 
    app.post(
        "/api/Custom/UploadTemuCodToSftp",
        [authJwt.verifyToken],
        controller.UploadTemuCodToSftp
    );
    app.get(
        "/api/order-settings",
        [authJwt.verifyToken],
        controller.orderSettings
    );
    app.post(
        "/api/settings",
        [authJwt.verifyToken],
        controller.updateSettings
    );
    app.post(
        "/api/Custom/GenerateTemuAdditionalReport",
        [authJwt.verifyToken],
        controller.GenerateTemuAdditionalReport
    );
    app.post(
        "/api/Custom/GetTemuAdditionalReportHistory",
        [authJwt.verifyToken],
        controller.GetTemuAdditionalReportHistory
    );
    
}