const { authJwt } = require("../middleware");
const controller = require("../controllers/master-service.controller");

module.exports = function (app) {
  app.use(function (req, res, next) {
    res.header(
      "Access-Control-Allow-Headers",
      "x-access-token, Origin, Content-Type, Accept"
    );
    next();
  });

  app.get(
    "/api/master-service",
    [authJwt.verifyToken],
    controller.getMasterServices
  );
  app.get(
    "/api/master-service-group",
    [authJwt.verifyToken],
    controller.getMasterServicesGroup
  );
  app.get(
    "/api/service-type-master/dropdown",
    [authJwt.verifyToken],
    controller.getServiceTypesDropDown
  );
  app.post(
    "/api/service-group-master",
    [authJwt.verifyToken],
    controller.createServiceGroup
  );
  app.get(
    "/api/service-type-master",
    [authJwt.verifyToken],
    controller.getServiceTypeMaster
  );
  app.post(
    "/api/service-type-master",
    [authJwt.verifyToken],
    controller.createServiceType
  );
  app.get(
    "/api/service-group-master/dropdown",
    [authJwt.verifyToken],
    controller.getServiceGroupDropDown
  );
  app.post(
    "/api/rate-service",
    [authJwt.verifyToken],
    controller.createRateService
  );
  app.get(
    "/api/rate-service",
    [authJwt.verifyToken],
    controller.getServiceRate
  );
  app.get(
    "/api/countries",
    [authJwt.verifyToken],
    controller.getCountries
  );
  app.get(
    "/api/governorates",
    [authJwt.verifyToken],
    controller.getGovernorates
  );
  app.get(
    "/api/internal-rate-service",
    [authJwt.verifyToken],
    controller.getRate_service
  );
  
  app.get(
    "/api/cities",
    [authJwt.verifyToken],
    controller.getCities
  );
  app.get(
    "/api/wilayat",
    [authJwt.verifyToken],
    controller.getOmanWilayat
  );
  app.get(
    "/api/oman-governorates/cities",
    [authJwt.verifyToken],
    controller.getOmanCity
  );
  app.get(
    "/api/oman-governorates/area",
    [authJwt.verifyToken],
    controller.getOmanArea
  );
  app.get(
    "/api/oman-governorates/zip-code",
    [authJwt.verifyToken],
    controller.getZipCode
  );
  app.get(
    "/api/billing-cycle",
    [authJwt.verifyToken],
    controller.getBillingCycle
  );
  app.post(
    "/api/master-user",
    [authJwt.verifyToken],
    controller.createClientMaster
 );
  app.post(
    "/api/user-clients/create-user",
    [authJwt.verifyToken],
    controller.createUser
 );
 app.get(
  "/api/client-master",
  [authJwt.verifyToken],
  controller.getClientMaster
);
 app.get(
  "/api/client-users",
  [authJwt.verifyToken],
  controller.getClienstUsers
);
 app.get(
  "/api/client-users-by-merchant",
  [authJwt.verifyToken],
  controller.getClientUsers
);
 app.get(
  "/api/show-client",
  [authJwt.verifyToken],
  controller.getClient
);
 app.post(
  "/api/edit-client",
  [authJwt.verifyToken],
  controller.editClientMaster
);
 app.get(
  "/api/client-master/pending-count",
  [authJwt.verifyToken],
  controller.getClientPendingCount
);
app.get(
  "/api/client-master/approve",
  [authJwt.verifyToken],
  controller.approveClient
);
  app.patch(
    "/api/rate-service",
    [authJwt.verifyToken],
    controller.editRateService
  );
  app.get(
    "/api/master-service/pending-count",
    [authJwt.verifyToken],
    controller.getMasterServicesPendingCount
  );
  app.get(
    "/api/rate-service/approve",
    [authJwt.verifyToken],
    controller.approveServiceMaster
  );
  app.get(
    "/api/rate-service-by-type",
    [authJwt.verifyToken],
    controller.getServiceRateByType
  );
  app.get(
    "/api/rate-service-by-group",
    [authJwt.verifyToken],
    controller.getServiceRateByGroup
    );
  app.get(
    "/api/fulfillment-clients",
    [authJwt.verifyToken],
    controller.getFulfillmentClients
  );
  app.get(
    "/api/available-integration",
    [authJwt.verifyToken],
    controller.getAvailableIntegration
  );
  app.get(
    "/api/client-integration-list",
    [authJwt.verifyToken],
    controller.getClientsIntegrationList
  );
  app.get(
    "/api/all-integration-codes",
    [authJwt.verifyToken],
    controller.getAllAvailableCodes
  );
  app.post(
    "/api/integration-clients",
    [authJwt.verifyToken],
    controller.createClientIntegration
  );
  app.get(
    "/api/not-integration-client",
    [authJwt.verifyToken],
    controller.getAllAvailableClients
  );
  app.post(
    "/api/amazon-fake-events-pusher",
    [authJwt.verifyToken],
    controller.pushAmazonFakeEvents
  );
  app.post(
      "/api/amazon-boe-file",
      [authJwt.verifyToken],
      controller.pushAmazonBoeFile
  );
};
