const { authJwt } = require("../middleware");
const controller = require("../controllers/master-service.controller");

module.exports = function (app) {
  app.use(function (req, res, next) {
    res.header(
      "Access-Control-Allow-Headers",
      "x-access-token, Origin, Content-Type, Accept"
    );
    next();
  });

  app.get(
    "/api/master-service",
    [authJwt.verifyToken],
    controller.getMasterServices
  );
  app.get(
    "/api/master-service-group",
    [authJwt.verifyToken],
    controller.getMasterServicesGroup
  );
  app.get(
    "/api/service-type-master/dropdown",
    [authJwt.verifyToken],
    controller.getServiceTypesDropDown
  );
  app.post(
    "/api/service-group-master",
    [authJwt.verifyToken],
    controller.createServiceGroup
  );
  app.get(
    "/api/service-type-master",
    [authJwt.verifyToken],
    controller.getServiceTypeMaster
  );
  app.post(
    "/api/service-type-master",
    [authJwt.verifyToken],
    controller.createServiceType
  );
  app.get(
    "/api/service-group-master/dropdown",
    [authJwt.verifyToken],
    controller.getServiceGroupDropDown
  );
  app.post(
    "/api/rate-service",
    [authJwt.verifyToken],
    controller.createRateService
  );
  app.get(
    "/api/rate-service",
    [authJwt.verifyToken],
    controller.getServiceRate
  );
  app.get(
    "/api/countries",
    [authJwt.verifyToken],
    controller.getCountries
  );
  app.get(
    "/api/governorates",
    [authJwt.verifyToken],
    controller.getGovernorates
  );
  app.get(
    "/api/internal-rate-service",
    [authJwt.verifyToken],
    controller.getRate_service
  );
  
  app.get(
    "/api/cities",
    [authJwt.verifyToken],
    controller.getCities
  );
  app.get(
    "/api/wilayat",
    [authJwt.verifyToken],
    controller.getOmanWilayat
  );
  app.get(
    "/api/oman-governorates/cities",
    [authJwt.verifyToken],
    controller.getOmanCity
  );
  app.get(
    "/api/oman-governorates/area",
    [authJwt.verifyToken],
    controller.getOmanArea
  );
  app.get(
    "/api/oman-governorates/zip-code",
    [authJwt.verifyToken],
    controller.getZipCode
  );
  app.get(
    "/api/billing-cycle",
    [authJwt.verifyToken],
    controller.getBillingCycle
  );
  app.post(
    "/api/master-user",
    [authJwt.verifyToken],
    controller.createClientMaster
 );
 app.get(
  "/api/client-master",
  [authJwt.verifyToken],
  controller.getClientMaster
);
  app.patch(
    "/api/rate-service",
    [authJwt.verifyToken],
    controller.editRateService
  );
  app.get(
    "/api/master-service/pending-count",
    [authJwt.verifyToken],
    controller.getMasterServicesPendingCount
  );
  app.get(
    "/api/rate-service/approve",
    [authJwt.verifyToken],
    controller.approveServiceMaster
  );
};