const { authJwt } = require("../middleware");
const controller = require("../controllers/master-city.controller");

module.exports = function (app) {
  app.use(function (req, res, next) {
    res.header(
      "Access-Control-Allow-Headers",
      "x-access-token, Origin, Content-Type, Accept"
    );
    next();
  });

  app.post(
    "/api/create-country",
    [authJwt.verifyToken],
    controller.createCountry
 );
  app.get(
    "/api/countries-master",
    [authJwt.verifyToken],
    controller.getCountriesMaster
  );  
  app.get(
    "/api/country",
    [authJwt.verifyToken],
    controller.getCountry
  );
  app.post(
    "/api/edit-country",
    [authJwt.verifyToken],
    controller.editCountry
  );  
  app.post(
    "/api/activate-country",
    [authJwt.verifyToken],
    controller.activateCountry
  );

  app.get(
    "/api/governorates-master",
    [authJwt.verifyToken],
    controller.getGovernoratesMaster
  );
  app.post(
    "/api/create-governorate",
    [authJwt.verifyToken],
    controller.createGovernorate
 );
  app.get(
    "/api/governorate",
    [authJwt.verifyToken],
    controller.getGovernorate
  );  
  app.get(
    "/api/governorate/countries",
    [authJwt.verifyToken],
    controller.getGovernorateByCountries
  );
  app.post(
    "/api/edit-governorate",
    [authJwt.verifyToken],
    controller.editGovernorate
  ); 

  app.get(
    "/api/wilayat-master",
    [authJwt.verifyToken],
    controller.getWilayatMaster
  );
  app.post(
    "/api/create-wilayat",
    [authJwt.verifyToken],
    controller.createWilayat
 );
  app.post(
    "/api/edit-wilayat",
    [authJwt.verifyToken],
    controller.editWilayat
  );
  app.get(
    "/api/show-wilayat",
    [authJwt.verifyToken],
    controller.getWilayat
  ); 
  app.get(
    "/api/cities-master",
    [authJwt.verifyToken],
    controller.getCitiesMaster
  );
  app.post(
    "/api/create-city",
    [authJwt.verifyToken],
    controller.createCity
 );
  app.get(
    "/api/city",
    [authJwt.verifyToken],
    controller.getCity
  );  
  app.get(
    "/api/cities/country",
    [authJwt.verifyToken],
    controller.getCitiesByCountry
  );  
  app.post(
    "/api/edit-city",
    [authJwt.verifyToken],
    controller.editCity
  );  
  app.post(
    "/api/activate-city",
    [authJwt.verifyToken],
    controller.activateCity
  );

  app.get(
    "/api/area-master",
    [authJwt.verifyToken],
    controller.getAreaMaster
  );
  app.post(
    "/api/create-area",
    [authJwt.verifyToken],
    controller.createArea
 );
  app.get(
    "/api/area",
    [authJwt.verifyToken],
    controller.getArea
  );  
  app.post(
    "/api/edit-area",
    [authJwt.verifyToken],
    controller.editArea
  );  
  app.post(
    "/api/activate-area",
    [authJwt.verifyToken],
    controller.activateArea
  );

  app.post(
    "/api/create-eventcode",
    [authJwt.verifyToken],
    controller.createEventCode
 );
  app.get(
    "/api/eventcodes",
    [authJwt.verifyToken],
    controller.getEventCodes
  );  
  app.get(
    "/api/eventcode",
    [authJwt.verifyToken],
    controller.getEventCode
  );
  app.post(
    "/api/edit-eventcode",
    [authJwt.verifyToken],
    controller.editEventCode
  );  
};