const { authJwt } = require("../middleware");
const controller = require("../controllers/printing.controller");
module.exports = function (app) {
    app.post(
        "/api/print/com-invoice",
        [authJwt.verifyToken],
        controller.generrateCommercialInvoice
    );
    app.post(
        "/api/print/bulk-awb",
        [authJwt.verifyToken],
        controller.generateBulkAwb
    );
    app.post(
        "/api/print/awb",
        [authJwt.verifyToken],
        controller.generateSingleAwb
    );
    app.post(
        "/api/print/bulk-awb-excel",
        [authJwt.verifyToken],
        controller.generrateCommercialInvoiceExcel
    );
    app.post(
        "/api/print/manifest",
        [authJwt.verifyToken],
        controller.generateManifest
    );
    app.post(
        "/api/print/ipickup-manifest",
        [authJwt.verifyToken],
        controller.generateIpickupManifest
    );
    app.post(
        "/api/print/generate-fulfillment-invoice",
        [authJwt.verifyToken],
        controller.generateFulFillmentInvoice
    );
    app.get(
        "/api/print/get-generated-invoices",
        [authJwt.verifyToken],
        controller.getGeneratedFulfillmentInvoices
    );
    app.post(
        "/api/print/sales-invoice",
        [authJwt.verifyToken],
        controller.generateSalesInvoice
    );
}
